package scaffold

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type InitOptions struct {
	Dir    string
	Module string
	Force  bool
}

type scaffoldFile struct {
	Path     string
	Template string
}

type templateData struct {
	Module string
}

func Init(opts InitOptions) error {
	module := strings.TrimSpace(opts.Module)
	if module == "" {
		return fmt.Errorf("module name is required")
	}
	if strings.ContainsAny(module, " \t\r\n") {
		return fmt.Errorf("module name must not contain whitespace")
	}
	dir := opts.Dir
	if dir == "" {
		dir = "."
	}

	files := backendFiles()
	if !opts.Force {
		for _, file := range files {
			path := filepath.Join(dir, file.Path)
			if _, err := os.Stat(path); err == nil {
				return fmt.Errorf("%s already exists", path)
			} else if !os.IsNotExist(err) {
				return err
			}
		}
	}

	data := templateData{Module: module}
	for _, file := range files {
		content, err := render(file.Template, data)
		if err != nil {
			return fmt.Errorf("render %s: %w", file.Path, err)
		}
		path := filepath.Join(dir, file.Path)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func render(source string, data templateData) ([]byte, error) {
	tmpl, err := template.New("scaffold").Parse(source)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func backendFiles() []scaffoldFile {
	return []scaffoldFile{
		{Path: "go.mod", Template: goModTemplate},
		{Path: "README.md", Template: readmeTemplate},
		{Path: ".env", Template: envTemplate},
		{Path: "cmd/api/main.go", Template: mainTemplate},
		{Path: "internal/app/register.go", Template: appRegisterTemplate},
		{Path: "internal/app/README.md", Template: appReadmeTemplate},
		{Path: "internal/app/health/module.go", Template: healthModuleTemplate},
	}
}

const goModTemplate = `module {{ .Module }}

go 1.25.0
`

const readmeTemplate = `# FBA Backend

Generated by ` + "`fbago init {{ .Module }}`" + `.

## Layout

- ` + "`cmd/api`" + `: HTTP entrypoint.
- ` + "`internal/app`" + `: project-owned business modules. Put admin, dict, order, payment, and other editable business code here.
- ` + "`.env`" + `: local defaults. Real system environment variables override this file.

Run:

` + "```bash" + `
go mod tidy
go run ./cmd/api
` + "```" + `
`

const envTemplate = `ENVIRONMENT=dev
FASTAPI_TITLE=FBA App
FASTAPI_API_V1_PATH=/api/v1
DATETIME_TIMEZONE=Asia/Shanghai
REALTIME_DISABLED=false
`

const mainTemplate = `package main

import (
	"context"
	"log"

	fba "github.com/yuWorm/fba-go"
	"github.com/yuWorm/fba-go/core/plugin"
	appmodules "{{ .Module }}/internal/app"
)

func main() {
	application, err := newApplication()
	if err != nil {
		log.Fatal(err)
	}
	if err := application.Run(context.Background()); err != nil {
		log.Fatal(err)
	}
}

func newApplication() (fba.Application, error) {
	opts, err := fba.LoadOptionsFromEnv()
	if err != nil {
		return nil, err
	}
	opts = opts.WithDefaults()
	application, err := fba.NewApplication(opts)
	if err != nil {
		return nil, err
	}

	registry := plugin.NewRegistry()
	if err := appmodules.Register(registry); err != nil {
		return nil, err
	}

	pluginContext := plugin.NewContext(plugin.ContextOptions{
		Container: application.Container(),
		Router:    application.HTTP(),
		APIGroup:  application.HTTP().Group(opts.App.APIBasePath),
		Config:    opts,
	})
	if err := registry.RegisterAll(pluginContext); err != nil {
		return nil, err
	}
	plugin.MountRoutes(pluginContext.APIGroup(), pluginContext.Routes(), plugin.WithContainer(pluginContext.Container()))

	return application, nil
}
`

const appRegisterTemplate = `package app

import (
	"github.com/yuWorm/fba-go/core/plugin"
	"{{ .Module }}/internal/app/health"
)

func Register(registry *plugin.Registry) error {
	modules := []plugin.Module{
		health.Module(),
	}
	for _, module := range modules {
		if err := registry.Add(module, plugin.ModeAuto); err != nil {
			return err
		}
	}
	return nil
}
`

const appReadmeTemplate = `# App Modules

This directory is project-owned. Business modules live here so the application can freely change routes, models, repositories, services, migrations, and permissions without forking remote packages.

Reusable capabilities can still be imported as external FBA plugins when they are truly generic.
`

const healthModuleTemplate = `package health

import (
	"github.com/gofiber/fiber/v3"
	"github.com/yuWorm/fba-go/core/plugin"
	"github.com/yuWorm/fba-go/core/response"
)

func Module() plugin.Module {
	return module{}
}

type module struct{}

func (module) Meta() plugin.Meta {
	return plugin.Meta{
		ID:          "health",
		Name:        "Health App Module",
		Version:     "0.1.0",
		Description: "Project-owned health module generated by fbago init.",
	}
}

func (module) Register(ctx plugin.Context) error {
	return plugin.RegisterRoutes(ctx, []plugin.Route{
		plugin.GET("/app/ping", "App ping", ping, plugin.Tags("app")),
	})
}

func ping(c fiber.Ctx) error {
	return c.JSON(response.Success(map[string]string{
		"status": "ok",
	}))
}
`
