package scaffold_test

import (
	"encoding/base64"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/yuWorm/fba-go/cmd/fbago/internal/scaffold"
	fbsecret "github.com/yuWorm/fba-go/cmd/fbago/internal/secret"
)

func TestInitWritesDefaultAdminScaffold(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("FBAGO_TEMPLATE_REPLACE", "")

	if err := scaffold.Init(scaffold.InitOptions{
		Dir:    dir,
		Module: "github.com/acme/backend",
	}); err != nil {
		t.Fatalf("Init() error = %v", err)
	}

	assertFileContains(t, filepath.Join(dir, "go.mod"), "module github.com/acme/backend")
	assertFileContains(t, filepath.Join(dir, "go.mod"), "github.com/yuWorm/fba-go-admin v0.1.4")
	assertFileContains(t, filepath.Join(dir, "go.mod"), "replace github.com/yuWorm/fba-go => ")
	assertFileNotContains(t, filepath.Join(dir, "go.mod"), "replace github.com/yuWorm/fba-go-admin =>")
	assertFileContains(t, filepath.Join(dir, "cmd/api/main.go"), `admin "github.com/yuWorm/fba-go-admin"`)
	assertFileContains(t, filepath.Join(dir, "cmd/api/main.go"), `"github.com/acme/backend/internal/generated"`)
	assertFileContains(t, filepath.Join(dir, "internal/generated/fba_plugins.gen.go"), "func RegisterPlugins")
	assertFileContains(t, filepath.Join(dir, "plugins.yaml"), "github.com/yuWorm/fba-go-admin/modules/admin")
	assertFileContains(t, filepath.Join(dir, "plugins.lock"), `"module": "github.com/yuWorm/fba-go-admin"`)
	assertFileContains(t, filepath.Join(dir, ".env"), "FASTAPI_API_V1_PATH=/api/v1")
	assertFileContains(t, filepath.Join(dir, ".env"), "ADMIN_BOOTSTRAP_PASSWORD=Admin@Local2026!")
	jwtSecret := envValue(t, filepath.Join(dir, ".env"), "TOKEN_SECRET_KEY")
	rawSecret, err := base64.RawURLEncoding.DecodeString(jwtSecret)
	if err != nil {
		t.Fatalf("decode generated JWT secret: %v", err)
	}
	if len(rawSecret) != fbsecret.DefaultBytes {
		t.Fatalf("generated JWT entropy = %d bytes, want %d", len(rawSecret), fbsecret.DefaultBytes)
	}
	if exampleSecret := envValue(t, filepath.Join(dir, ".env.example"), "TOKEN_SECRET_KEY"); exampleSecret != "" {
		t.Fatalf("example JWT secret = %q, want empty placeholder", exampleSecret)
	}
	if examplePassword := envValue(t, filepath.Join(dir, ".env.example"), "ADMIN_BOOTSTRAP_PASSWORD"); examplePassword != "" {
		t.Fatalf("example Admin bootstrap password = %q, want empty placeholder", examplePassword)
	}
	assertFileContains(t, filepath.Join(dir, ".env.example"), "# CORS")
	assertFileContains(t, filepath.Join(dir, ".fbago.yaml"), "version: 1")
	assertFileContains(t, filepath.Join(dir, ".fbago.yaml"), "name: admin")
	assertFileContains(t, filepath.Join(dir, ".fbago.yaml"), "source: embedded")
	assertFileContains(t, filepath.Join(dir, ".fbago.yaml"), "core_version: v0.0.0")
	assertFileContains(t, filepath.Join(dir, "Makefile"), "$(GOENV) $(GO) mod tidy")
	assertFileContains(t, filepath.Join(dir, "Makefile"), "$(GOENV) $(GO) build -o $(BIN_DIR)/$(APP) ./cmd/api")
	assertFileContains(t, filepath.Join(dir, "README.md"), "--template admin")
	assertFileNotExists(t, filepath.Join(dir, "internal", "app"))
	assertFileNotExists(t, filepath.Join(dir, "internal", "runtime"))
	assertFileNotExists(t, filepath.Join(dir, "plugins"))
	assertFileNotExists(t, filepath.Join(dir, "fbago-template.yaml"))
}

func TestInitUsesExplicitCoreReplaceInBasicTemplate(t *testing.T) {
	dir := t.TempDir()

	if err := scaffold.Init(scaffold.InitOptions{
		Dir:         dir,
		Module:      "github.com/acme/backend",
		Template:    "basic",
		CoreReplace: "../fba-go",
	}); err != nil {
		t.Fatalf("Init() error = %v", err)
	}

	assertFileContains(t, filepath.Join(dir, "go.mod"), "require github.com/yuWorm/fba-go v0.0.0")
	assertFileContains(t, filepath.Join(dir, "go.mod"), "replace github.com/yuWorm/fba-go => ../fba-go")
}

func TestInitUsesExplicitCoreVersionInBasicTemplate(t *testing.T) {
	dir := t.TempDir()

	if err := scaffold.Init(scaffold.InitOptions{
		Dir:         dir,
		Module:      "github.com/acme/backend",
		Template:    "basic",
		CoreVersion: "v1.2.3",
	}); err != nil {
		t.Fatalf("Init() error = %v", err)
	}

	assertFileContains(t, filepath.Join(dir, "go.mod"), "require github.com/yuWorm/fba-go v1.2.3")
}

func TestListTemplatesIncludesBuiltins(t *testing.T) {
	templates, err := scaffold.ListTemplates()
	if err != nil {
		t.Fatalf("ListTemplates() error = %v", err)
	}
	if !contains(templates, "basic") {
		t.Fatalf("templates = %v, missing basic", templates)
	}
	if !contains(templates, "admin") {
		t.Fatalf("templates = %v, missing admin", templates)
	}
}

func TestInitSupportsExplicitBasicTemplate(t *testing.T) {
	dir := t.TempDir()

	if err := scaffold.Init(scaffold.InitOptions{
		Dir:      dir,
		Module:   "github.com/acme/backend",
		Template: "basic",
	}); err != nil {
		t.Fatalf("Init() error = %v", err)
	}

	assertFileContains(t, filepath.Join(dir, "internal/app/health/module.go"), `Description: "Project-owned health module generated by fbago init."`)
}

func TestInitSupportsLocalPathTemplate(t *testing.T) {
	dir := t.TempDir()
	templateDir := filepath.Join(t.TempDir(), "external-admin")
	writeTemplateFile(t, templateDir, "go.mod.tmpl", "module [[ .Module ]]\n\ngo 1.25.0\n")
	writeTemplateFile(t, templateDir, "cmd/api/main.go.tmpl", `package main

import "fmt"

func main() {
	fmt.Println("[[ .Module ]]")
}
`)
	writeTemplateFile(t, templateDir, "Makefile", "test:\n\tgo test ./...\n")
	writeTemplateFile(t, templateDir, "env.tmpl", "FASTAPI_API_V1_PATH=/api/v1\n")

	if err := scaffold.Init(scaffold.InitOptions{
		Dir:      dir,
		Module:   "github.com/acme/backend",
		Template: templateDir,
	}); err != nil {
		t.Fatalf("Init() error = %v", err)
	}

	assertFileContains(t, filepath.Join(dir, "go.mod"), "module github.com/acme/backend")
	assertFileContains(t, filepath.Join(dir, "cmd/api/main.go"), `fmt.Println("github.com/acme/backend")`)
	assertFileContains(t, filepath.Join(dir, ".env"), "FASTAPI_API_V1_PATH=/api/v1")
	assertFileContains(t, filepath.Join(dir, "Makefile"), "go test ./...")
}

func TestInitRewritesRunnableLocalTemplateModule(t *testing.T) {
	dir := t.TempDir()
	templateDir := filepath.Join(t.TempDir(), "admin-template")
	writeTemplateFile(t, templateDir, ".fbago-template.yaml", "module: github.com/acme/fba-go-template/admin\n")
	writeTemplateFile(t, templateDir, "go.mod", "module github.com/acme/fba-go-template/admin\n\ngo 1.25.0\n")
	writeTemplateFile(t, templateDir, "fbago.yaml.tmpl", `version: 1

template:
  module: [[ .Module ]]
  source_module: [[ .TemplateModule ]]
  source: [[ .TemplateSource ]]

managed:
  - name: admin
    kind: app
    mode: source
    path: internal/app/admin
    source_path: internal/app/admin
`)
	writeTemplateFile(t, templateDir, "cmd/api/main.go", `package main

import "github.com/acme/fba-go-template/admin/internal/app"

func main() {
	app.Register(nil)
}
`)
	writeTemplateFile(t, templateDir, "README.md.tmpl", "Generated from [[ .TemplateModule ]] to [[ .Module ]]\n")

	if err := scaffold.Init(scaffold.InitOptions{
		Dir:      dir,
		Module:   "github.com/acme/backend",
		Template: templateDir,
	}); err != nil {
		t.Fatalf("Init() error = %v", err)
	}

	assertFileContains(t, filepath.Join(dir, "go.mod"), "module github.com/acme/backend")
	assertFileContains(t, filepath.Join(dir, "cmd/api/main.go"), `"github.com/acme/backend/internal/app"`)
	assertFileContains(t, filepath.Join(dir, "README.md"), "Generated from github.com/acme/fba-go-template/admin to github.com/acme/backend")
	assertFileContains(t, filepath.Join(dir, ".fbago.yaml"), "module: github.com/acme/backend")
	assertFileContains(t, filepath.Join(dir, ".fbago.yaml"), "source_module: github.com/acme/fba-go-template/admin")
	assertFileContains(t, filepath.Join(dir, ".fbago.yaml"), "source: local")
	assertFileContains(t, filepath.Join(dir, ".fbago.yaml"), "path: internal/app/admin")
	assertFileNotExists(t, filepath.Join(dir, ".fbago-template.yaml"))
}

func TestInitPrefersRenderableTemplateWhenTargetPathCollides(t *testing.T) {
	dir := t.TempDir()
	templateDir := filepath.Join(t.TempDir(), "admin-template")
	writeTemplateFile(t, templateDir, ".fbago-template.yaml", "module: github.com/acme/fba-go-template/admin\n")
	writeTemplateFile(t, templateDir, "go.mod", "module github.com/acme/fba-go-template/admin\n\nreplace github.com/yuWorm/fba-go => ../../fba-go\n")
	writeTemplateFile(t, templateDir, "go.mod.tmpl", "module [[ .Module ]]\n\nrequire github.com/yuWorm/fba-go [[ .CoreVersion ]]\n")

	if err := scaffold.Init(scaffold.InitOptions{
		Dir:         dir,
		Module:      "github.com/acme/backend",
		Template:    templateDir,
		CoreVersion: "v1.2.3",
	}); err != nil {
		t.Fatalf("Init() error = %v", err)
	}

	assertFileContains(t, filepath.Join(dir, "go.mod"), "module github.com/acme/backend")
	assertFileContains(t, filepath.Join(dir, "go.mod"), "require github.com/yuWorm/fba-go v1.2.3")
	assertFileNotContains(t, filepath.Join(dir, "go.mod"), "replace github.com/yuWorm/fba-go")
}

func TestInitFormatsGeneratedGoAfterModuleRewrite(t *testing.T) {
	dir := t.TempDir()
	templateDir := filepath.Join(t.TempDir(), "admin-template")
	writeTemplateFile(t, templateDir, ".fbago-template.yaml", "module: github.com/acme/fba-go-template/admin\n")
	writeTemplateFile(t, templateDir, "cmd/api/main.go", `package main

import (
	fba "github.com/yuWorm/fba-go"
	"github.com/acme/fba-go-template/admin/internal/app"
)

var _, _ = fba.NewApplication, app.Register
`)

	if err := scaffold.Init(scaffold.InitOptions{
		Dir:      dir,
		Module:   "github.com/acme/backend",
		Template: templateDir,
	}); err != nil {
		t.Fatalf("Init() error = %v", err)
	}

	assertFileContains(t, filepath.Join(dir, "cmd/api/main.go"), `import (
	"github.com/acme/backend/internal/app"
	fba "github.com/yuWorm/fba-go"
)`)
}

func TestInitSupportsRemoteGitTemplateWithSubdirAndRef(t *testing.T) {
	dir := t.TempDir()
	repoDir := t.TempDir()
	writeTemplateFile(t, repoDir, "admin/.fbago-template.yaml", "module: github.com/acme/fba-go-template/admin\n")
	writeTemplateFile(t, repoDir, "admin/go.mod", "module github.com/acme/fba-go-template/admin\n\ngo 1.25.0\n")
	writeTemplateFile(t, repoDir, "admin/cmd/api/main.go", `package main

import "github.com/acme/fba-go-template/admin/internal/app"

func main() {
	app.Register(nil)
}
`)
	writeTemplateFile(t, repoDir, "admin/README.md.tmpl", "Generated [[ .Module ]] from [[ .TemplateModule ]]\n")
	runGit(t, repoDir, "init")
	runGit(t, repoDir, "add", ".")
	runGit(t, repoDir, "-c", "user.name=fbago", "-c", "user.email=fbago@example.invalid", "commit", "-m", "init")
	runGit(t, repoDir, "tag", "admin/v0.1.0")
	t.Setenv("FBAGO_TEMPLATE_CACHE_DIR", t.TempDir())

	if err := scaffold.Init(scaffold.InitOptions{
		Dir:      dir,
		Module:   "github.com/acme/backend",
		Template: "file://" + filepath.ToSlash(repoDir) + "//admin@admin/v0.1.0",
	}); err != nil {
		t.Fatalf("Init() error = %v", err)
	}

	assertFileContains(t, filepath.Join(dir, "go.mod"), "module github.com/acme/backend")
	assertFileContains(t, filepath.Join(dir, "cmd/api/main.go"), `"github.com/acme/backend/internal/app"`)
	assertFileContains(t, filepath.Join(dir, "README.md"), "Generated github.com/acme/backend from github.com/acme/fba-go-template/admin")
	assertFileNotExists(t, filepath.Join(dir, ".git"))
}

func TestInitSkipsLocalTemplateRepositoryArtifacts(t *testing.T) {
	dir := t.TempDir()
	templateDir := filepath.Join(t.TempDir(), "external-admin")
	writeTemplateFile(t, templateDir, "go.mod.tmpl", "module [[ .Module ]]\n")
	writeTemplateFile(t, templateDir, ".git/config", "repository metadata\n")
	writeTemplateFile(t, templateDir, ".cache/go-build/cache.txt", "build cache\n")
	writeTemplateFile(t, templateDir, "bin/api", "compiled binary\n")
	writeTemplateFile(t, templateDir, ".DS_Store", "finder metadata\n")

	if err := scaffold.Init(scaffold.InitOptions{
		Dir:      dir,
		Module:   "github.com/acme/backend",
		Template: templateDir,
	}); err != nil {
		t.Fatalf("Init() error = %v", err)
	}

	assertFileContains(t, filepath.Join(dir, "go.mod"), "module github.com/acme/backend")
	assertFileNotExists(t, filepath.Join(dir, ".git"))
	assertFileNotExists(t, filepath.Join(dir, ".cache"))
	assertFileNotExists(t, filepath.Join(dir, "bin"))
	assertFileNotExists(t, filepath.Join(dir, ".DS_Store"))
}

func TestInitUsesExplicitTemplateReplace(t *testing.T) {
	t.Setenv("FBAGO_TEMPLATE_REPLACE", "../ignored-template")
	dir := t.TempDir()
	templateDir := filepath.Join(t.TempDir(), "template")
	writeTemplateFile(t, templateDir, ".fbago-template.yaml", "module: github.com/acme/template\n")
	writeTemplateFile(t, templateDir, "go.mod.tmpl", `module [[ .Module ]]

go 1.25.0

require [[ .TemplateModule ]] [[ .TemplateVersion ]]
[[ if .TemplateReplace ]]replace [[ .TemplateModule ]] => [[ .TemplateReplace ]]
[[ end ]]`)

	if err := scaffold.Init(scaffold.InitOptions{
		Dir:             dir,
		Module:          "github.com/acme/backend",
		Template:        templateDir,
		TemplateReplace: "../explicit-template",
	}); err != nil {
		t.Fatalf("Init() error = %v", err)
	}

	assertFileContains(t, filepath.Join(dir, "go.mod"), "github.com/acme/template v0.0.0")
	assertFileContains(t, filepath.Join(dir, "go.mod"), "replace github.com/acme/template => ../explicit-template")
	assertFileNotContains(t, filepath.Join(dir, "go.mod"), "../ignored-template")
}

func TestInitUsesTemplateReplaceEnvironment(t *testing.T) {
	t.Setenv("FBAGO_TEMPLATE_REPLACE", "../environment-template")
	dir := t.TempDir()
	templateDir := filepath.Join(t.TempDir(), "template")
	writeTemplateFile(t, templateDir, ".fbago-template.yaml", "module: github.com/acme/template\n")
	writeTemplateFile(t, templateDir, "go.mod.tmpl", `module [[ .Module ]]

go 1.25.0

require [[ .TemplateModule ]] [[ .TemplateVersion ]]
[[ if .TemplateReplace ]]replace [[ .TemplateModule ]] => [[ .TemplateReplace ]]
[[ end ]]`)

	if err := scaffold.Init(scaffold.InitOptions{
		Dir:      dir,
		Module:   "github.com/acme/backend",
		Template: templateDir,
	}); err != nil {
		t.Fatalf("Init() error = %v", err)
	}

	assertFileContains(t, filepath.Join(dir, "go.mod"), "replace github.com/acme/template => ../environment-template")
}

func TestInitRejectsSymbolicLinkInLocalTemplate(t *testing.T) {
	templateDir := t.TempDir()
	writeTemplateFile(t, templateDir, ".fbago-template.yaml", "module: github.com/acme/template\n")
	outside := filepath.Join(t.TempDir(), "secret.txt")
	if err := os.WriteFile(outside, []byte("must not be copied"), 0o600); err != nil {
		t.Fatalf("write outside secret: %v", err)
	}
	if err := os.Symlink(outside, filepath.Join(templateDir, "leak.txt")); err != nil {
		t.Skipf("symbolic links are unavailable: %v", err)
	}

	dir := t.TempDir()
	err := scaffold.Init(scaffold.InitOptions{
		Dir:      dir,
		Module:   "github.com/acme/backend",
		Template: templateDir,
	})
	if err == nil {
		t.Fatal("Init() succeeded, want symbolic-link rejection")
	}
	if !strings.Contains(err.Error(), "symbolic link") {
		t.Fatalf("error = %q, want symbolic-link rejection", err.Error())
	}
	assertFileNotExists(t, filepath.Join(dir, "leak.txt"))
}

func TestInitCannotWriteThroughDestinationSymbolicLink(t *testing.T) {
	templateDir := t.TempDir()
	writeTemplateFile(t, templateDir, ".fbago-template.yaml", "module: github.com/acme/template\n")
	writeTemplateFile(t, templateDir, "escape/payload.txt", "must stay inside project\n")

	dir := t.TempDir()
	outside := t.TempDir()
	if err := os.Symlink(outside, filepath.Join(dir, "escape")); err != nil {
		t.Skipf("symbolic links are unavailable: %v", err)
	}
	err := scaffold.Init(scaffold.InitOptions{
		Dir:      dir,
		Module:   "github.com/acme/backend",
		Template: templateDir,
		Force:    true,
	})
	if err == nil {
		t.Fatal("Init() succeeded, want destination symbolic-link rejection")
	}
	if !strings.Contains(err.Error(), "symbolic link") {
		t.Fatalf("error = %q, want symbolic-link rejection", err.Error())
	}
	assertFileNotExists(t, filepath.Join(outside, "payload.txt"))
}

func TestInitRejectsUnknownTemplate(t *testing.T) {
	err := scaffold.Init(scaffold.InitOptions{
		Dir:      t.TempDir(),
		Module:   "github.com/acme/backend",
		Template: "missing",
	})
	if err == nil {
		t.Fatal("Init() succeeded, want unknown template error")
	}
	if !strings.Contains(err.Error(), `unknown template "missing"`) {
		t.Fatalf("error = %q, want unknown template", err.Error())
	}
}

func TestInitRejectsMissingModule(t *testing.T) {
	err := scaffold.Init(scaffold.InitOptions{Dir: t.TempDir()})
	if err == nil {
		t.Fatal("Init() succeeded, want missing module error")
	}
	if !strings.Contains(err.Error(), "module name is required") {
		t.Fatalf("error = %q, want module name error", err.Error())
	}
}

func TestInitDoesNotOverwriteExistingGoMod(t *testing.T) {
	dir := t.TempDir()
	goMod := filepath.Join(dir, "go.mod")
	if err := os.WriteFile(goMod, []byte("module existing\n"), 0o644); err != nil {
		t.Fatalf("write existing go.mod: %v", err)
	}

	err := scaffold.Init(scaffold.InitOptions{
		Dir:    dir,
		Module: "github.com/acme/backend",
	})
	if err == nil {
		t.Fatal("Init() succeeded, want overwrite error")
	}
	if !strings.Contains(err.Error(), "already exists") {
		t.Fatalf("error = %q, want already exists", err.Error())
	}
}

func envValue(t *testing.T, filename string, key string) string {
	t.Helper()
	content, err := os.ReadFile(filename)
	if err != nil {
		t.Fatalf("read %s: %v", filename, err)
	}
	prefix := key + "="
	for _, line := range strings.Split(string(content), "\n") {
		if value, ok := strings.CutPrefix(line, prefix); ok {
			return value
		}
	}
	t.Fatalf("%s has no %s entry", filename, key)
	return ""
}

func assertFileContains(t *testing.T, path string, want string) {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if !strings.Contains(string(content), want) {
		t.Fatalf("%s = %q, missing %q", path, string(content), want)
	}
}

func assertFileNotContains(t *testing.T, path string, unwanted string) {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if strings.Contains(string(content), unwanted) {
		t.Fatalf("%s = %q, should not contain %q", path, string(content), unwanted)
	}
}

func assertFileNotExists(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err == nil {
		t.Fatalf("%s exists, want it to be skipped", path)
	} else if !os.IsNotExist(err) {
		t.Fatalf("stat %s: %v", path, err)
	}
}

func writeTemplateFile(t *testing.T, root string, rel string, content string) {
	t.Helper()
	path := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func runGit(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, output)
	}
}

func contains(items []string, want string) bool {
	for _, item := range items {
		if item == want {
			return true
		}
	}
	return false
}
