package plugin

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

func WriteLock(path string, result ScanResult) error {
	content, err := json.MarshalIndent(result, "", "  ")
	if err != nil {
		return err
	}
	content = append(content, '\n')
	return writeGeneratedFile(path, content)
}

func GenerateRegistration(path string, packageName string, result ScanResult) error {
	content, err := registrationContent(packageName, result)
	if err != nil {
		return err
	}
	return writeGeneratedFile(path, content)
}

func registrationContent(packageName string, result ScanResult) ([]byte, error) {
	if packageName == "" {
		packageName = "generated"
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by fbago. DO NOT EDIT.\n")
	buf.WriteString("package " + packageName + "\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\tplugin \"github.com/yuWorm/fba-go/core/plugin\"\n")
	for i, item := range result.Plugins {
		fmt.Fprintf(&buf, "\tplugin%d %q\n", i, item.Module)
	}
	buf.WriteString(")\n\n")
	buf.WriteString("func RegisterPlugins(reg *plugin.Registry) error {\n")
	for i, item := range result.Plugins {
		fmt.Fprintf(&buf, "\tif err := reg.Add(plugin%d.FBAPlugin(), plugin.%s); err != nil {\n", i, item.ModeConstant())
		buf.WriteString("\t\treturn err\n")
		buf.WriteString("\t}\n")
	}
	buf.WriteString("\treturn nil\n")
	buf.WriteString("}\n")

	return format.Source(buf.Bytes())
}

func writeGeneratedFile(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, content, 0o644)
}

func (p Plugin) ModeConstant() string {
	switch p.Mode {
	case "disabled":
		return "ModeDisabled"
	case "pure_dependency":
		return "ModePureDependency"
	default:
		return "ModeAuto"
	}
}
