package plugin_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	fbplugin "github.com/yuWorm/fba-go/cmd/fbago/internal/plugin"
	coreplugin "github.com/yuWorm/fba-go/core/plugin"
)

func TestScanMergesManifestLocalAndImportsDeterministically(t *testing.T) {
	dir := t.TempDir()
	pluginsDir := filepath.Join(dir, "plugins")
	mustWrite(t, filepath.Join(dir, "plugins.yaml"), []byte(`
plugins:
  - id: admin
    module: github.com/acme/fba-plugin-admin
    mode: auto
    swagger: admin.swagger.json
  - id: oauth2-sdk
    module: github.com/acme/fba-plugin-oauth2-sdk
    mode: pure_dependency
`))
	mustWrite(t, filepath.Join(pluginsDir, "order", "plugin.yaml"), []byte(`
id: order
module: github.com/acme/backend/plugins/order
mode: auto
`))
	mustWrite(t, filepath.Join(dir, "main.go"), []byte(`package main

import (
	_ "github.com/acme/fba-plugin-dict"
)
`))

	result, err := fbplugin.Scan(fbplugin.ScanOptions{
		Modes:      []string{"manifest", "local", "imports"},
		ModuleDir:  dir,
		PluginsDir: pluginsDir,
		Manifest:   filepath.Join(dir, "plugins.yaml"),
	})
	if err != nil {
		t.Fatalf("Scan() error = %v", err)
	}

	got := pluginIDs(result.Plugins)
	const want = "admin,dict,oauth2-sdk,order"
	if got != want {
		t.Fatalf("plugin ids = %q, want %q", got, want)
	}
	if result.Plugins[2].Mode != coreplugin.ModePureDependency {
		t.Fatalf("oauth2-sdk mode = %q, want pure_dependency", result.Plugins[2].Mode)
	}
}

func TestWriteLockAndGenerateRegistration(t *testing.T) {
	dir := t.TempDir()
	result := fbplugin.ScanResult{Plugins: []fbplugin.Plugin{
		{ID: "admin", Module: "github.com/acme/fba-plugin-admin", Mode: coreplugin.ModeAuto, Swagger: "admin.swagger.json"},
		{ID: "oauth2-sdk", Module: "github.com/acme/fba-plugin-oauth2-sdk", Mode: coreplugin.ModePureDependency},
	}}
	lockPath := filepath.Join(dir, "plugin_manifest.lock")
	outPath := filepath.Join(dir, "fba_plugins.gen.go")

	if err := fbplugin.WriteLock(lockPath, result); err != nil {
		t.Fatalf("WriteLock() error = %v", err)
	}
	content, err := os.ReadFile(lockPath)
	if err != nil {
		t.Fatalf("ReadFile(lock) error = %v", err)
	}
	var lock map[string][]map[string]any
	if err := json.Unmarshal(content, &lock); err != nil {
		t.Fatalf("Unmarshal(lock) error = %v", err)
	}
	if lock["plugins"][0]["id"] != "admin" {
		t.Fatalf("lock = %s", content)
	}

	if err := fbplugin.GenerateRegistration(outPath, "generated", result); err != nil {
		t.Fatalf("GenerateRegistration() error = %v", err)
	}
	generated, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("ReadFile(generated) error = %v", err)
	}
	text := string(generated)
	for _, expected := range []string{
		"// Code generated by fbago. DO NOT EDIT.",
		"package generated",
		`plugin0 "github.com/acme/fba-plugin-admin"`,
		"reg.Add(plugin0.FBAPlugin(), plugin.ModeAuto)",
		"reg.Add(plugin1.FBAPlugin(), plugin.ModePureDependency)",
	} {
		if !strings.Contains(text, expected) {
			t.Fatalf("generated code missing %q:\n%s", expected, text)
		}
	}
}

func pluginIDs(plugins []fbplugin.Plugin) string {
	ids := make([]string, 0, len(plugins))
	for _, plugin := range plugins {
		ids = append(ids, plugin.ID)
	}
	return strings.Join(ids, ",")
}

func mustWrite(t *testing.T, path string, content []byte) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("MkdirAll(%s) error = %v", path, err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		t.Fatalf("WriteFile(%s) error = %v", path, err)
	}
}
